### ISSUE TITLE
About Data Generation

### ISSUE THREAD

**Issue by BraveDrXuTF** [ashiq24/UNO#1]
Thank you for the excellent work! I want to ask some questions about NS data generation, I run the code without any modification and get a file of a dozen GB, however I'm not sure how many samples are in the file. How to determine the number of samples in the file?

**Comment by ashiq24** [comment]
You can control them by setting the value of variable N in the data generation code. (line 128)
```python 
#Number of solutions to generate
N = 1200
```

Also, you can use the data loader script to load and see the shape of the tensor.
